[Mon Jul 27 14:59:42.330365 2020] [wsgi:error] [pid 114352:tid 140412833330944] [remote 93.117.124.222:19909] Not Found: /favicon.ico
[Mon Jul 27 15:00:23.367268 2020] [wsgi:error] [pid 114352:tid 140412749403904] [remote 93.117.124.222:19930] teacher1
[Mon Jul 27 15:00:23.367953 2020] [wsgi:error] [pid 114352:tid 140412749403904] [remote 93.117.124.222:19930] teacher1
[Mon Jul 27 15:00:26.681175 2020] [wsgi:error] [pid 114352:tid 140412833330944] [remote 93.117.124.222:19931] Not Found: /teacher/favorite.ico
[Mon Jul 27 15:00:54.503810 2020] [wsgi:error] [pid 114352:tid 140412833330944] [remote 93.117.124.222:19961] Not Found: /teacher/excercise/favorite.ico
Exception ignored in: <function BaseEventLoop.__del__ at 0x7fb46060e700>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <function Local.__del__ at 0x7fb461593550>
Traceback (most recent call last):
  File "/home/amir/school/venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fb461593550>
Traceback (most recent call last):
  File "/home/amir/school/venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fb461593550>
Traceback (most recent call last):
  File "/home/amir/school/venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function BaseEventLoop.__del__ at 0x7f310ad9a700>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <function Local.__del__ at 0x7f310bd0a550>
Traceback (most recent call last):
  File "/home/amir/school/venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f310bd0a550>
Traceback (most recent call last):
  File "/home/amir/school/venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f310bd0a550>
Traceback (most recent call last):
  File "/home/amir/school/venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Mon Jul 27 15:22:09.373143 2020] [wsgi:error] [pid 114989:tid 140173040445184] [remote 93.117.124.222:20682] teacher1
[Mon Jul 27 15:22:09.373755 2020] [wsgi:error] [pid 114989:tid 140173040445184] [remote 93.117.124.222:20682] teacher1
